# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              XELI
logo:               'https://xeli.me/images/logo.png'
description:        DigiSec for Youth Workers
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://xeli.me/' # The base hostname & protocol for your site
twitter:            https://twitter.com/xeli_me
facebook:           https://www.facebook.com/xeli.me
instagram:          https://www.instagram.com/xeli.me

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  XELI:
    name:     XELI
    bio:      
    gravatar: 
    email:    
    website:  
    github:   
    twitter:  
